version: "1.0"
services:
  tekkenframes:
    command: "mix phx.server"
    build:
      context: $TEKKENFRAMES_DIR
      dockerfile: $TEKKENFRAMES_DIR/Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
